### ISSUE TITLE
the role 'mysql' was not found

### ISSUE THREAD

**Issue by turbo124** [do-community/ansible-role-mysql#1]
running the example playbook throws the role 'mysql' was not found

is there an accompanying mysql role for this playbook?

**Comment by imchairmanm** [comment]
@turbo124 Hey there.  I'm actually a bit confused by this one. This repository is for a MySQL role.  Are you asking about the site.yml playbook [here](https://github.com/do-community/do-blueprint-mysqlgrouprepl) (which references this role)?  If so, the `setup.yml` playbook is supposed to fetch the required roles (including this one) and perform quite a few other initialization actions.  Take a look at the [quickstart](https://github.com/do-community/do-blueprint-mysqlgrouprepl#quickstart) if you haven't already to get the repository set up with all of the dependencies.  I hope that helps.
